name: appli_recette
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  drift: ^2.23.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_image_compress: ^2.4.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  go_router: ^17.1.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.3
  rxdart: ^0.28.0
  sqlite3_flutter_libs: ^0.5.28
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  bloc_lint: ^0.3.7
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.22
  build_runner: ^2.4.14
  drift_dev: ^2.23.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.3
  very_good_analysis: ^10.2.0

flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/static/Nunito-Regular.ttf
        - asset: assets/fonts/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/static/Nunito-Bold.ttf
          weight: 700

  assets:
    - assets/fonts/static/
